# app/config/security.yml


security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        PP\UserBundle\Entity\User: sha512
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    
    providers:
        main:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main_login:
            pattern: ^/login$
            anonymous: true
        main:
            pattern:      ^/
            anonymous:    true
            provider:     main
            form_login:
                    login_path: fos_user_security_login
                    check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     /
            remember_me:
                secret:     %secret%
        
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        
    