<?php

namespace PP\CoreBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AstuceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AstuceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPageAstuces($page, $nbrePage) {
        $query = $this->createQueryBuilder('a')
                ->orderBy('a.id', 'desc')
                ->getQuery();

        $query->setFirstResult(($page - 1) * $nbrePage)->setMaxResults($nbrePage);

        return new Paginator($query, true);
    }
}
