<?php

namespace PP\CoreBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends \Doctrine\ORM\EntityRepository {

    public function getPageComments($page, $nbrePage) {
        $query = $this->createQueryBuilder('c')
                ->leftJoin('c.recette', 'r')
                ->addSelect('r')
                ->leftJoin('c.user', 'u')
                ->addSelect('u')
                ->orderBy('c.id', 'desc')
                ->getQuery();

        $query->setFirstResult(($page - 1) * $nbrePage)->setMaxResults($nbrePage);

        return new Paginator($query, true);
    }

}
