<?php

namespace PP\CoreBundle\Repository;

/**
 * PhotoProfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoProfilRepository extends \Doctrine\ORM\EntityRepository
{
}
