<?php

namespace PP\CoreBundle\Repository;

/**
 * profileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class profileRepository extends \Doctrine\ORM\EntityRepository
{
}
